# Check out https://docs.codemagic.io/getting-started/building-a-native-android-app/ for more information

workflows:
    android-app:# Rivan957
        name: Android App# Jembott
        scripts:
            - ./gradlew assembleDebug
        artifacts:
            - app/build/outputs/**/*.apk
